vti_encoding:SR|utf8-nl
vti_author:SR|IUSR_PRUE
vti_modifiedby:SR|IUSR_PRUE
vti_timecreated:TR|25 Feb 2003 22:05:16 -0000
vti_timelastmodified:TR|15 May 2003 19:57:47 -0000
vti_filesize:IR|13898
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_extenderversion:SR|4.0.2.5526
vti_backlinkinfo:VX|macro/listnotasrelacionadas.asp macro/listseccionesredactores.asp macro/gennota.asp
vti_nexttolasttimemodified:TR|15 May 2003 18:04:47 -0000
vti_title:SR|Sistema Ivmaker / elcomercioperu.com / Listado de notas
vti_syncwith_server-ec4\:80/ivmaker30:TR|28 Apr 2003 15:51:01 -0000
vti_cacheddtm:TX|15 May 2003 19:57:47 -0000
vti_cachedlinkinfo:VX|Q|../Include/Css/stilo.css S|../Include/Js/fConfirmAction.js A|../Macro/ListNotas.asp H|EditNotas.asp H|GenNota.asp S|../Image/html.gif H|ListNotasRelacionadas.asp S|../Image/subnotas.gif H|<%=sDominio%><%=fUrlNota(iCodNota,\\ oConn)%> S|../Image/htmla.gif H|javascript:fMuestraDivModulos('<%=iCodNota%>',\\ 'block') H|JavaScript:fConfirmAction('ElimNotas.asp?CodPub=<%=icodPublicacion%>&CodSec=<%=iCodSeccion%>&EstArch=<%=sEstadoArchivo%>&CodNota=<%=iCodNota%>',\\ '¿Está\\ seguro\\ de\\ eliminar\\ esta\\ nota?') S|../Image/papelera.gif H|javascript:document.frmListNota.ScrollAction.value='<%=(iPrimeraPagina\\ -\\ 1)%>';document.frmListNota.PagIni.value='<%=(iPrimeraPagina-iNumPagLinks)-1%>';\\ document.frmListNota.submit() H|javascript:document.frmListNota.ScrollAction.value='<%=iLinkPage%>';\\ document.frmListNota.PagIni.value='<%=(iPrimeraPagina)%>';\\ document.frmListNota.submit() H|javascript:document.frmListNota.ScrollAction.value='<%=iLinkPage%>';document.frmListNota.PagIni.value='<%=(iUltimaPagina+1)%>';\\ document.frmListNota.submit() H|../Macro/IngrNotas.asp H|Javascript:location.href='GenSeccion.asp?CodPub=<%=iCodPublicacion%>&CodSec=<%=iCodSeccion%>&EstArch=<%=sEstadoArchivo%>&UrlRetorno=<%=Server.URLEncode("ListNotas.asp")%>' H|Javascript:location.href='GenIndiceSeccion.asp?CodPub=<%=iCodPublicacion%>&CodSec=<%=iCodSeccion%>&EstArch=<%=sEstadoArchivo%>&UrlRetorno=<%=Server.URLEncode("ListNotas.asp")%>' H|Javascript:document.frmListNota.submit() H|../Macro/ListSeccionesRedactores.asp
vti_cachedsvcrellinks:VX|FQUS|Include/Css/stilo.css FSUS|Include/Js/fConfirmAction.js FAUS|Macro/ListNotas.asp FHUS|macro/EditNotas.asp FHUS|macro/GenNota.asp FSUS|Image/html.gif FHUS|macro/ListNotasRelacionadas.asp FSUS|Image/subnotas.gif UHUS|<%=sDominio%><%=fUrlNota(iCodNota,\\ oConn)%> FSUS|Image/htmla.gif SHUS|javascript:fMuestraDivModulos('<%=iCodNota%>',\\ 'block') SHUS|JavaScript:fConfirmAction('ElimNotas.asp?CodPub=<%=icodPublicacion%>&CodSec=<%=iCodSeccion%>&EstArch=<%=sEstadoArchivo%>&CodNota=<%=iCodNota%>',\\ '¿Está\\ seguro\\ de\\ eliminar\\ esta\\ nota?') FSUS|Image/papelera.gif SHUS|javascript:document.frmListNota.ScrollAction.value='<%=(iPrimeraPagina\\ -\\ 1)%>';document.frmListNota.PagIni.value='<%=(iPrimeraPagina-iNumPagLinks)-1%>';\\ document.frmListNota.submit() SHUS|javascript:document.frmListNota.ScrollAction.value='<%=iLinkPage%>';\\ document.frmListNota.PagIni.value='<%=(iPrimeraPagina)%>';\\ document.frmListNota.submit() SHUS|javascript:document.frmListNota.ScrollAction.value='<%=iLinkPage%>';document.frmListNota.PagIni.value='<%=(iUltimaPagina+1)%>';\\ document.frmListNota.submit() FHUS|Macro/IngrNotas.asp SHUS|Javascript:location.href='GenSeccion.asp?CodPub=<%=iCodPublicacion%>&CodSec=<%=iCodSeccion%>&EstArch=<%=sEstadoArchivo%>&UrlRetorno=<%=Server.URLEncode("ListNotas.asp")%>' SHUS|Javascript:location.href='GenIndiceSeccion.asp?CodPub=<%=iCodPublicacion%>&CodSec=<%=iCodSeccion%>&EstArch=<%=sEstadoArchivo%>&UrlRetorno=<%=Server.URLEncode("ListNotas.asp")%>' SHUS|Javascript:document.frmListNota.submit() FHUS|Macro/ListSeccionesRedactores.asp
vti_cachedtitle:SR|Sistema Ivmaker / elcomercioperu.com / Listado de notas
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" marginheight="0" marginwidth="0" leftmargin="0" topmargin="0">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
